version: '3.7'
services:
  creating:
    build: war
    volumes:
      - type: volume
        source: share
        target: /boxfuse-sample-java-war-hello/target/
  
  prod:
    image: tomcat:jre8-alpine
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps/
    ports:
      - "80:8080"

volumes:
  share: